name: .Net CI Runner

on:
  push:
    paths:
      - 'apis/poi/*'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'apis/poi/*'
defaults:
  run:
    working-directory: ./apis/poi
    
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      run: dotnet test --no-restore --verbosity normal tests/UnitTests
    - name: Create Issue
      if: failure() # OR Check a bool variable you create and toggle as needed
      uses: dacbd/create-issue-action@v1
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
    - name: Build and push Container to ACR
      uses: azure/docker-login@v1
      with:
        login-server: openhack5tb2l2k6acr.azurecr.io
        username: "openhack5tb2l2k6acr"
        password: "ckPonxIqkKo=T3jU3w1TxEdFcQmrKihU"
    - run: |
         docker build web -t openhack5tb2l2k6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
         docker push openhack5tb2l2k6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure App Services
      uses: Azure/webapps-deploy@v2
      with:
        app-name: openhack5tb2l2k6poi
        slot-name: staging
        images:  openhack5tb2l2k6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
  healthcheck:
    runs-on: ubuntu-latest
    steps:
    - name: healthtest
      run: | 
         ./polling.sh "https://openhack5tb2l2k6poi-staging.azurewebsites.net/api/healthcheck/poi"

   
        
