name: .Net CI Runner

on:
  push:
    branches: [ NPE ]
    paths:
      - 'apis/poi/*'
  pull_request:
    branches: [ NPE ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: .NET Test
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov
    - name: Create Issue
      if: failure() # OR Check a bool variable you create and toggle as needed
      uses: JasonEtco/create-an-issue@masterenv      
