name: .Net CI Runner

on:
  push:
    paths:
      - 'apis/poi/*'
  pull_request:
    paths:
      - 'apis/poi/*'

defaults:
  run:
    working-directory: ./apis/poi
    
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore 
    - name: Build Docker Image
      uses: azure/docker-login@v1
      with:
        login-server: openhack5tb2l2k6acr.azurecr.io
        username: "openhack5tb2l2k6acr"
        password: "ckPonxIqkKo=T3jU3w1TxEdFcQmrKihU"
    - run: |
         docker build web -t openhack5tb2l2k6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }} 
         docker push openhack5tb2l2k6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal tests/UnitTests
    - name: Create Issue
      if: failure() # OR Check a bool variable you create and toggle as needed
      uses: dacbd/create-issue-action@v1
      with:
        token: ${{ github.token }}
        title: Action workflow failed.

        
