name: .Net CI Runner

on:
  push:
    paths:
      - 'apis/poi/*'
  pull_request:
    paths:
      - 'apis/poi/*'

defaults:
  run:
    working-directory: ./apis/poi
    
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      run: dotnet test --no-restore --verbosity normal tests/UnitTests
    - name: Create Issue
      if: failure() # OR Check a bool variable you create and toggle as needed
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
